### ISSUE TITLE
Hello, how to operate on the mobile phone?

### ISSUE THREAD

**Issue by sdhiw2** [anthonyliu0417/biptPassGenNew#2]

**Comment by anthonyliu0417** [comment]
You need to build a Apache/Nginx + MySQL/Oracle + php environment on a Windows or Linux server first. Then clone this project and put the whole folder into the web directory of Apache/Nginx. Make sure you have changed the user name and password of database to yours on index.php. Then you can access the program through any browser. Enjoy  :)

**Comment by sdhiw2** [comment]
Thank you for your patience, but I have another new problem, after the PHP environment is configured, the following error message appears in the running code: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: ֪


在2022-11-08 10:26:45，Anthony ***@***.***写道：

You need to build a Apache/Nginx + MySQL/Oracle + php environment on a Windows or Linux server first. Then clone this project and put the whole folder into the web directory of Apache/Nginx. Make sure you have changed the user name and password of database to yours on index.php. Then you can access the program through any browser. Enjoy :)

**Comment by anthonyliu0417** [comment]
You can get more info about this problem at issue #3 , thx.
